import Head from "next/head";

import Navigation from "../components/Navigation/Navigation";
import ConversationCard from "../components/Chat/ConversationCard";
import MessagingComponent from "../components/Chat/MessagingComponent";
import Footer from "../components/Footer/Footer";

export default function Chat() {
  return (
    <div className="min-h-screen overflow-y-hidden">
      <Head>
        <title>
          Safeanzeigen - Wir bringen Ihre Kleinanzeigen mit Sicherheit groß
          raus!s
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#2f70e9" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.webmanifest" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </Head>

      <Navigation />
      <div className="w-full h-min">
        <div className="flex h-min">
          <div className="flex-1 w-full h-screen bg-gray-100">
            <div className="container flex flex-col w-11/12 m-auto h-min main-body">
              <div className="flex flex-row py-4 flex-2 lg:invisible">
                <span className="inline-block text-gray-700 align-bottom xl:hidden hover:text-gray-900">
                  <span className="block w-6 h-6 p-1 rounded-full hover:bg-gray-400">
                    <svg
                      className="w-4 h-4"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                  </span>
                </span>
              </div>
              <div className="flex flex-col flex-1 main">
                <div className="hidden lg:block heading flex-2">
                  <h1 className="mb-4 text-3xl text-gray-700">
                    Konversationen
                  </h1>
                </div>
                <div className="flex flex-1 h-full">
                  <div className="flex-col hidden w-1/3 pr-6 sidebar lg:flex flex-2">
                    <div
                      className="flex-1 h-full p-4 overflow-auto overflow-x-hidden"
                      style={{ maxHeight: "75vh" }}
                    >
                      {/* MAP Conversations HERE */}
                      <ConversationCard
                        conversationName="Kamera in gutem Zustand"
                        conversationLastDate="25. Mai"
                        publishedNameOfAd="Max Mustermann"
                        unreadMessage={true}
                      />
                      <ConversationCard
                        conversationName="Kamera in gutem Zustand"
                        conversationLastDate="25. Mai"
                        publishedNameOfAd="Max Mustermann"
                        unreadMessage={true}
                      />
                      <ConversationCard
                        conversationName="Kamera in gutem Zustand"
                        conversationLastDate="25. Mai"
                        publishedNameOfAd="Max Mustermann"
                        unreadMessage={true}
                      />
                      <ConversationCard
                        conversationName="Kamera in gutem Zustand"
                        conversationLastDate="25. Mai"
                        publishedNameOfAd="Max Mustermann"
                        unreadMessage={true}
                      />
                      <ConversationCard
                        conversationName="Kamera in gutem Zustand"
                        conversationLastDate="25. Mai"
                        publishedNameOfAd="Max Mustermann"
                        unreadMessage={true}
                      />
                    </div>
                  </div>
                  <MessagingComponent
                    nameOfAd="Kamera in gutem Zustand"
                    adURL="safeanzeigen/anzeige/158515"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
