import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>
          Safeanzeigen - Wir bringen Ihre Kleinanzeigen mit Sicherheit groß
          raus!
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#2f70e9" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.webmanifest" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png"></link>
      </Head>

      {/* Navigation */}
      {/* Main Page */}
      {/* Section 1 */}
      {/* Section 2 */}
      {/* Footer */}
    </div>
  );
}
